server:
  port: 8090
  servlet:
    contextPath: /api

spring:
  datasource:
    url: jdbc:mysql://47.98.232.164:3306/layui?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=UTC&useSSL=false
    username: root
    password: Hh123!456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.zero
  mapper-locations: classpath*:mybatis/*Mapper.xml

